services:
  # ------------- broker (choreographed only) -------------
  rabbitmq:
    image: rabbitmq:3.13-management
    ports: ["5672:5672", "15672:15672"]
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- CHOREOGRAPHER SAGA SERVICES ---
  choreographer-order-service:
    build: {context: ., dockerfile: backend/orchestrator_saga/services/order_service/Dockerfile}
    environment:
      ORDER_SERVICE_PORT: 8081
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      INVENTORY_SERVICE_URL: http://choreographer-inventory-service:8082
    depends_on: {rabbitmq: {condition: service_healthy}}

  choreographer-inventory-service:
    build: {context: ., dockerfile: backend/choreographer_saga/services/inventory_service/Dockerfile}
    environment:
      INVENTORY_SERVICE_PORT: 8082
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on: {rabbitmq: {condition: service_healthy}}

  choreographer-payment-service:
    build: {context: ., dockerfile: backend/choreographer_saga/services/payment_service/Dockerfile}
    environment:
      PAYMENT_SERVICE_PORT: 8083
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on: { rabbitmq: { condition: service_healthy } }

  choreographer-auth-service:
    build: {context: ., dockerfile: backend/choreographer_saga/services/auth_service/Dockerfile}
    environment:
      AUTH_SERVICE_PORT: 8084
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on: { rabbitmq: { condition: service_healthy } }

  # --- ORCHESTRATOR SAGA SERVICES ---
  orchestrator-order-service:
    build: {context: ., dockerfile: backend/orchestrator_saga/services/order_service/Dockerfile}
    environment:
      ORDER_SERVICE_PORT: 8081

  orchestrator-inventory-service:
    build: {context: ., dockerfile: backend/orchestrator_saga/services/inventory_service/Dockerfile}
    environment:
      INVENTORY_SERVICE_PORT: 8082

  orchestrator-payment-service:
    build: {context: ., dockerfile: backend/orchestrator_saga/services/payment_service/Dockerfile}
    environment:
      PAYMENT_SERVICE_PORT: 8083

  orchestrator-auth-service:
    build: {context: ., dockerfile: backend/choreographer_saga/services/auth_service/Dockerfile}
    environment:
      AUTH_SERVICE_PORT: 8084

  # MAIN ORCHESTRATOR SERVICE
  orchestrator:
    build: {context: ., dockerfile: backend/orchestrator_saga/Dockerfile}
    environment:
      ServerPort: 8080
      OrderServiceURL: http://orchestrator-order-service:8081
      InventoryServiceURL: http://orchestrator-inventory-service:8082
      PaymentServiceURL: http://orchestrator-payment-service:8083

  # ---------- GATEWAY and FRONTEND (always active) ----------
  # --- API Gateway ---
  api-gateway:
    build: {context: ., dockerfile: backend/gateway/Dockerfile}
    ports: ["8000:8000"]
    environment:
      GATEWAY_PORT: 8000
      CHOREOGRAPHER_INVENTORY_BASE_URL: http://choreographer-inventory-service:8082
      ORCHESTRATOR_INVENTORY_BASE_URL:  http://orchestrator-inventory-service:8082
      CHOREOGRAPHER_ORDER_BASE_URL:     http://choreographer-order-service:8081
      ORCHESTRATOR_ORDER_BASE_URL:      http://orchestrator-order-service:8081
      CHOREOGRAPHER_ORDER_SERVICE_URL:  http://choreographer-order-service:8081/create_order
      ORCHESTRATOR_MAIN_SERVICE_URL:    http://orchestrator:8080/create_order
      CHOREOGRAPHER_AUTH_BASE_URL:      http://choreographer-auth-service:8084
      ORCHESTRATOR_AUTH_BASE_URL:       http://orchestrator-auth-service:8084
    depends_on:
      - choreographer-inventory-service
      - orchestrator-inventory-service

  # --- Frontend Service ---
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes: [ "./frontend:/app" ]
    ports: [ "8090:3000" ]
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"
    depends_on: { api-gateway: { condition: service_started } }

networks:
  default:

volumes:
  rabbitmq_data:
  rabbitmq_log: